name: AWS S3 Sync

on: 
  push:
    branches:
      - 'feature/make_git_practice'
  

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: test
        run: echo $TEST_VALUE

      # - name: "Configure AWS credentials"
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.S3_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.S3_SECRET_ACCESS_KEY }}
      #     aws-region: ap-northeast-1
      # - name: S3 sync
      #   working-directory: git
      #   run: aws s3 sync . s3://congratulations-marriage --delete --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers